image:
  name: python:3.10

before:
  - sudo apt-get update
  - sudo apt-get install -y libgl1-mesa-dev
  - python -m pip install --upgrade pip

tasks:
    command: python -m pip install -r requirements.txt
    init: true
